# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    cached_timestamp = current_timestamp
    match(type: "adhoc", readonly: is_ci)
    build_app(scheme: "OnePercentWin")
    # todo: inject api token from jenkins
    commit = last_git_commit
    deploygate(
      api_token: "f6090463008eb32f50a78dbe144e5980cb25a3c7",
      user: "davidlamys",
      ipa: "./OnePercentWin.ipa",
      message: commit[:message]
    )
    add_git_tag(tag: "#{cached_timestamp}")
    push_git_tags(tag: "å#{cached_timestamp}")
  
  end

end

def current_timestamp
  Time.now.strftime("%y%m%d%H%M")
end
